Change display of EnergyProblem variable
TulipaEnergy/TulipaEnergyModel.jl pull request #413
Opened 2024-01-17 12:59 UTC by gnawin

# Pull request details

## Describe the changes made in this pull request

Change the display of EnergyProblem variable, now it shows 
- solved
- objective_value

## List of related issues or pull requests

Closes #321 

## Collaboration confirmation

As a contributor I confirm

- [ ] I read and followed the instructions in README.dev.md
- [ ] The documentation is up to date with the changes introduced in this Pull Request (or NA)
- [ ] Tests are passing
- [ ] Lint is passing

2024-01-17 14:02 UTC, datejada reviewed
@gnawin thanks! please double-check the case when the model is infesible

2024-01-17 14:28 UTC, gnawin commented
> @gnawin thanks! please double-check the case when the model is infesible

The relevant options of the `EnergyProblem` is now reset at the end of `create_model!`

2024-01-17 15:10 UTC, abelsiqueira requested changes
Thanks. I made some small suggestions.

2024-01-17 15:10 UTC, abelsiqueira commented on src/structures.jl
> +"""
```suggestion
```

2024-01-17 15:10 UTC, abelsiqueira commented on src/structures.jl
> +    print(io, "Objective_value: ", ep.objective_value)
```suggestion
    println(io, "EnergyProblem:")
    println(io, "  - Model created: ", !isnothing(ep.model))
    println(io, "  - Solved: ", ep.solved)
    println(io, "  - Termination status: ", ep.termination_status)
    println(io, "  - Objective_value: ", ep.objective_value)
```

2024-01-18 08:49 UTC, abelsiqueira approved these changes

2024-01-18 08:49 UTC, merged