Don't use unqualified using and update README.dev.md with guidelines
TulipaEnergy/TulipaEnergyModel.jl pull request #533
Opened 2024-03-12 11:30 UTC by abelsiqueira

## Describe the changes made in this pull request

using Package should not be used anymore. Instead, explicitly use
using Package: A, B, C to load objects A, B, and C. Also, don't
do that for all objects, only obvious candidates. More information
is included in the README.dev.md new section on code format guidelines.

## List of related issues or pull requests

Closes #431

## Collaboration confirmation

As a contributor I confirm

- [x] I read and followed the instructions in README.dev.md
- [ ] The documentation is up to date with the changes introduced in this Pull Request (or NA)
- [x] Tests are passing
- [x] Lint is passing

2024-03-12 13:03 UTC, abelsiqueira commented
This needs to be rebased after #532

2024-03-13 09:35 UTC, clizbe requested changes
Just one little edit, the rest looks great!
Makes the code a bit longer, but I think it actually makes it more understandable.

2024-03-13 09:35 UTC, clizbe commented on README.dev.md
> +We will try to follow these developing and reviewing.
```suggestion
We will try to follow these during development and reviews.
```

2024-03-13 11:49 UTC, abelsiqueira commented
Thanks for the review, I've updated, and re-requested

2024-03-13 13:52 UTC, clizbe approved these changes
Great!

2024-03-13 13:53 UTC, merged