Create new variable and constraints for the `use_binary_storage_method`
TulipaEnergy/TulipaEnergyModel.jl pull request #645
Opened 2024-05-14 14:10 UTC by datejada

# Pull request details

## Describe the changes made in this pull request

Create the new variables and constraints according to #640 in the model to avoid charging and discharging simultaneously for energy storage assets.

## List of related issues or pull requests

Closes #639 

## Collaboration confirmation

As a contributor I confirm

-   [ ] I read and followed the instructions in README.dev.md
-   [ ] The documentation is up to date with the changes introduced in this Pull Request (or NA)
-   [ ] Tests are passing
-   [ ] Lint is passing

2024-05-14 14:19 UTC, datejada commented on src/create-model.jl
@abelsiqueira, this PR is just taking baby steps, but I wanted to double-check with you about this first change. It works, but I feel it can be done better (or more efficiently). Would you happen to have any suggestions?

2024-05-19 21:06 UTC, datejada commented
@abelsiqueira, the PR is ready for your review. The code has room for improvement (see the benchmark results), but formulation-wise, it returns the constraints and variables we expect. Depending on your comments, I will either try to do it myself (it is more effective) or ask Ni if it is more complicated.

2024-05-22 08:35 UTC, abelsiqueira requested changes
I made some comments. Haven't seem many opportunities to improve, would need to profile to see.
However, since you're creating a whole new dataframe and running the `add` function, it will slow down.

2024-05-22 08:35 UTC, abelsiqueira commented on src/create-model.jl
> +    agg = v -> sum(v) / length(v)
```suggestion
    agg = Statistics.mean
```
Maybe this works?

2024-05-22 08:35 UTC, abelsiqueira commented on src/create-model.jl
> +    )
I think a valid solution here is to append the value of `graph[a].use_binary_storage_method` to `df_is_charging` - I am reading this out of order, so I might have commented in another file already when you read this.
The idea here is to create a new column in `df_is_charging` then change to something like

```Julia
sub_df_is_charging_binary = subset(
  df_is_charging,
  :asset => ByRow(in(Asb)),
  :use_binary_storage_method => ByRow(==(:binary)),
  view=true
)
```

This should be somewhat more efficient.

2024-05-22 08:35 UTC, abelsiqueira commented on src/constraints/capacity.jl
> +        end for row in eachrow(dataframes[:highest_out]) if
I think here you want to change the `if` to the end of the `for`, like the other `if`?

2024-05-22 08:35 UTC, abelsiqueira commented on src/constraints/capacity.jl
> +        incoming_flow_highest_in_resolution[row.index] != 0
Same as above

2024-05-22 08:35 UTC, abelsiqueira commented on src/constraints/capacity.jl
> +        outgoing_flow_highest_out_resolution[row.index] != 0
Same as above

2024-05-22 08:35 UTC, abelsiqueira commented on src/constraints/capacity.jl
> +        outgoing_flow_highest_out_resolution[row.index] != 0
Same as above

2024-05-22 08:35 UTC, abelsiqueira commented on src/constraints/capacity.jl
> +        incoming_flow_highest_in_resolution[row.index] != 0
Same as above

2024-05-22 08:35 UTC, abelsiqueira commented on src/constraints/capacity.jl
> +        end for row in eachrow(dataframes[:highest_in]) if
Same as above

2024-05-25 15:55 UTC, datejada commented
@abelsiqueira Thanks for the review. I have committed the changes according to the review. Let me know if you have more suggestions; otherwise, please, when you review it, merge the branch 😄

2024-05-28 04:43 UTC, abelsiqueira approved these changes
THanks

2024-05-28 04:44 UTC, merged