Refactor timeframes, assets, and flows to use DuckDB for input data
TulipaEnergy/TulipaEnergyModel.jl pull request #712
Opened 2024-07-31 14:30 UTC by datejada

# Pull request details

## Describe the changes made in this pull request

To use DuckDB instead of tablee

## List of related issues or pull requests

Closes #710 

## Collaboration confirmation

As a contributor I confirm

-   [ ] I read and followed the instructions in README.dev.md
-   [ ] The documentation is up to date with the changes introduced in this Pull Request (or NA)
-   [ ] Tests are passing
-   [ ] Lint is passing

2024-08-01 11:59 UTC, suvayu requested changes
Seems like the default for `get_table` should be without `Val(:raw)`, and to get a df pass `Val(:df)`.

2024-08-01 11:59 UTC, suvayu commented on src/io.jl
> +    timeframe = Timeframe(num_periods, TulipaIO.get_table(connection, "rep_periods_mapping"))
```suggestion
    num_periods, = DuckDB.query(connection, "SELECT MAX(period) AS period FROM rep_periods_mapping")

    timeframe = Timeframe(num_periods.period, TulipaIO.get_table(connection, "rep_periods_mapping"))
```
Is this better?

You could also not rename it with `AS ...`, and instead use `num_periods[1]`.

2024-08-02 06:10 UTC, datejada commented
@suvayu, thanks for the review and suggestion 😄 I think we need to re-evaluate all these changes made during this week, given the results from the benchmarks in the latest PRs. @abelsiqueira has the PR #720 to compare performance. Let's review the big picture in the next meeting and decide how to continue.

2024-08-02 08:05 UTC, suvayu approved these changes

2024-08-05 14:06 UTC, merged